#!/bin/bash

# Retrieve arguments
domain=$1
path=$2


# Check domain/path availability
sudo yunohost app checkurl $domain$path -a tagspaces
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


# Copy files to the right place
final_path=/var/www/tagspaces
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path



# Set permissions to tagspaces directory
sudo mkdir -p $final_path/logs

sudo chown -hR www-data:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/tagspaces.conf

sed -i "s@NAMETOCHANGE@tagspaces@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/tagspaces.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

finalphpini=/etc/php5/fpm/conf.d/20-tagspaces.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini
sudo chmod 644 $finalphpini

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
