#!/bin/bash

domain=$(sudo yunohost app setting tagspaces domain)
path=$(sudo yunohost app setting tagspaces path)

deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
final_path=/var/www/tagspaces
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/main.inc.php $final_path/config/
sudo cp ../conf/main.inc.php $final_path/config/defaults.inc.php
sudo cp ../conf/db.inc.php $final_path/config/


sudo mkdir -p $final_path/logs
sudo chown -R www-data: $final_path

sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/tagspaces.conf

sed -i "s@NAMETOCHANGE@tagspaces@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/tagspaces.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

finalphpini=/etc/php5/fpm/conf.d/20-tagspaces.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini
sudo chmod 644 $finalphpini

sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf

